includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/DN4.yaml

way_num: 5
shot_num: 1
query_num: 15
episode_size: 1
train_episode: 2000
test_episode: 600

device_ids: 2
n_gpu: 1
epoch: 200

backbone:
  name: Conv64F
  kwargs:
    is_flatten: False
    is_feature: False
    leaky_relu: True
    negative_slope: 0.2
    last_pool: False

# backbone:
#   name: resnet12
#   kwargs:
#     maxpool_last2: False
#     is_flatten: False

# backbone:
#   name: resnet18
#   kwargs:
#     is_flatten: False
#     avg_pool: False
#     last_block_stride: 1

# backbone:
#   name: WRN
#   kwargs:
#     depth: 28
#     widen_factor: 10
#     avg_pool: False
#     is_flatten: False