includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/losses.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/dn4_classifier.yaml
  - backbones/Conv64F.yaml

backbone:
  name: Conv64F
  kwargs:
    is_flatten: False
    is_feature: False
    leaky_relu: True
    negative_slope: 0.2
    last_pool: False
