includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/MAML.yaml
  - backbones/resnet12.yaml

data_root: /data/fewshot/miniImageNet--ravi

optimizer:
  name: Adam
  kwargs:
    lr: 1e-3
  other: ~

backbone:
  name: Conv64F
  kwargs:
    is_flatten: True
    is_feature: False
    leaky_relu: False
    negative_slope: 0.2
    last_pool: True

classifier:
  name: MAML
  kwargs:
    inner_param:
      lr: 1e-2
      train_iter: 5
      test_iter: 10
    feat_dim: 1600


# backbone:
#   name: resnet12
#   kwargs:
#     keep_prob: 0.0

# classifier:
#   name: MAML
#   kwargs:
#     inner_param:
#       lr: 1e-2
#       train_iter: 5
#       test_iter: 10
#     feat_dim: 640


# backbone:
#   name: resnet18
#   kwargs: ~

# classifier:
#   name: MAML
#   kwargs:
#     inner_param:
#       lr: 1e-2
#       train_iter: 5
#       test_iter: 10
#     feat_dim: 512


# backbone:
#   name: WRN
#   kwargs:
#     depth: 28
#     widen_factor: 10

# classifier:
#   name: MAML
#   kwargs:
#     inner_param:
#       lr: 1e-2
#       train_iter: 5
#       test_iter: 10
#     feat_dim: 640
