includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml

data_root: /data/yxs/miniImageNet--ravi
# data_root: /data/yxs/tiered_imagenet

discriminative: True

device_ids: 7
n_gpu: 1

epoch: 200
train_episode: 2000
test_episode: 600

workers: 16

way_num: 5
shot_num: 5
query_num: 15

episode_size: 4

optimizer:
  name: Adam
  kwargs:
    lr: 0.0001
    weight_decay: 5e-4
  other: ~

# backbone:
#   name: Conv64F
#   kwargs:
#     is_flatten: True
#     is_feature: False
#     leaky_relu: True
#     negative_slope: 0.2
#     last_pool: True

# classifier:
#   name: VERSA
#   kwargs:
#     feat_dim: 1600
#     d_theta: 256
#     sample_num: 10
#     drop_rate: 0.5

backbone:
  name: resnet12
  kwargs: ~

classifier:
  name: VERSA
  kwargs:
    feat_dim: 640
    hid_dim: 640
    sample_num: 10


# backbone:
#   name: resnet18
#   kwargs: ~

# classifier:
#   name: VERSA
#   kwargs:
#     feat_dim: 512
#     hid_dim: 512
#     sample_num: 10


# backbone:
#   name: WRN
#   kwargs:
#     depth: 28
#     widen_factor: 10

# classifier:
#   name: VERSA
#   kwargs:
#     feat_dim: 640
#     hid_dim: 640
#     sample_num: 10
